export default {
  ASIDE_EXPAND: 'EXPRESS_ASIDE_EXPAND',
  ASIDE_COLLAPSE: 'EXPRESS_ASIDE_COLLAPSE',
  ASIDE_COLLAPSED_BYVALUE: 'EXPRESS_ASIDE_COLLAPSED_BYVALUE',
  GET_PRODUCT: "GET_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
};
